# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  commitPrefix:
    - pattern: "^(\\d+)-.*$"
      replace: "[#$1] "
  pagers:
    - externalDiffCommand: difft --display=inline --color=always
    - pager: delta --dark --paging=never --diff-so-fancy
customCommands:
  - key: 'F'
    context: 'files'
    command: 'git-absorb'
    description: 'Absorb staged files'
